/**
 * Types and schemas for the Daily Site static renderer.
 *
 * Defines the input shape produced by `loadDailySiteData` and the options
 * accepted by `renderSite`.
 */

import { z } from "zod";
import type {
	AggregatedItem,
	FeedsOutput,
	HomepageOutput,
	SiteConfig,
	SourcesOutput,
	ThemesOutput,
} from "./daily-site.js";

/** Metadata about a rendered daily archive. */
export const dailySiteMetaSchema = z.object({
	version: z.string(),
	date: z.string(),
	generated_at: z.string(),
	meta: z.object({
		total_calls: z.number().int(),
		successful_calls: z.number().int(),
		failed_calls: z.number().int(),
		total_items: z.number().int(),
	}),
});

/** Parsed `meta.json`. */
export type DailySiteMeta = z.infer<typeof dailySiteMetaSchema>;

/** Pages generated by the renderer. */
export type DailySitePage = "index" | "themes" | "sources" | "feeds";

/** All data required to render a daily site. */
export interface DailySiteRenderInput {
	/** Archive date in YYYY-MM-DD format. */
	date: string;
	/** Parsed `meta.json`. */
	meta: DailySiteMeta;
	/** Parsed `config/site.yaml`. */
	siteConfig: SiteConfig;
	/** Full items indexed by `id`. */
	items: Map<string, AggregatedItem>;
	/** Parsed `homepage.json`. */
	homepage: HomepageOutput;
	/** Parsed `sources.json`. */
	sources: SourcesOutput;
	/** Parsed `feeds.json`. */
	feeds: FeedsOutput;
	/** Parsed `themes.json`. */
	themes: ThemesOutput;
}

/** Options for `renderSite`. */
export interface DailySiteRenderOptions {
	/** Suppress per-file progress output. */
	quiet?: boolean;
	/** Optional logger for progress and errors. */
	logger?: import("../lib/logger.js").Logger;
}
